### ISSUE TITLE
Move seneca-auth-* module chain to this org

### ISSUE THREAD

**Issue by AdrianRossouw** [Concorda/concorda#62]
The next set of work will require us to be able to patch seneca-auth with security fixes as they come up.
The plan is to move all of them to this org, and make sure we have all the access needed before we run into blockers that require third parties to release modules.

@mcdonnelldean

**Comment by mcdonnelldean** [comment]
What do you need from me to make this happen @AdrianRossouw. This is a logical move. These modules are critical to Concorda and as such it should 'own' them.

**Comment by AdrianRossouw** [comment]
These modules should (by now) be part of the senecajs group, or in the seneca-bot's care.

could you please check with naomi and get move requests made for them.
Also please check that you have added myself and mircea to the npm owners list.

**Comment by mcdonnelldean** [comment]
I'll handle this so and close the issue when done.

**Comment by mcdonnelldean** [comment]
@AdrianRossouw There are no more modules in the SenecaJS Org now. If I missed anything reopen and let me know.
